version: "3.9"

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:5432/productdb
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - backend

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      - POSTGRES_USER=zahra
      - POSTGRES_PASSWORD=zahra
      - POSTGRES_DB=productdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:

volumes:
  pgdata:
